<?php

namespace Acme\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    public function recherche($user,$chaine)
    {
         $qb = $this->createQueryBuilder('u')
                   ->select('friends')
                   ->field('username')->equals($user->getid())
                   ->field('friends.username')->equals($chaine);
        return $qb->getQuery()->execute();
    }
}