fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

     
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile  
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

acme_user_user:
     resource: routing/user.yml
     prefix: /user


chat_welcome:
    path:     /
    defaults: { _controller: AcmeUserBundle:Friend:index }



add_friend_manual:
    pattern: /addfreidnmanual
    defaults: { _controller: "AcmeUserBundle:Friend:add" } 